name: okerr
description: A library for Result type.
version: 0.1.0
homepage: https://github.com/erayerdin/okerr
repository: https://github.com/erayerdin/okerr
issue_tracker: https://github.com/erayerdin/okerr/issues
documentation: https://github.com/erayerdin/okerr/blob/master/README.md

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^1.10.0
  test: ^1.16.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: